# Site settings
title: Emir Al-Kafagi's CV
description: Emir Al-Kafagi's CV
favicon: /assets/img/avatar.JPG
baseurl: http://www.emiralkafagi.me/cv
url: http://www.emiralkafagi.me/cv
rss_url: /blog/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Emir Al-Kafagi
  title: Geek, Designer, PC guy
  address: Skopje, Macedonia
  email: info@emiralkafagi.me
  link: http://emiralkafagi.me
  github: emirmkd
  linkedin: https://mk.linkedin.com/in/emiralkafagi
  twitter: emirtgeg33k
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Finzsoft Solutions Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Northeastern University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Macedonian
      proficiency: Native
    - language2:
      name: English
      proficiency: Highly proficient
    - language3:
      name: German
      proficiency: Beginner
  programmingSkills:
    - skill1:
      name: Photoshop
      percentage: 80%
    - skill2:
      name: Illustrator
      percentage: 60%
    - skill3:
      name: After Effects
      percentage: 40%
    - skill4:
      name: HTML/CSS
      percentage: 50%
    - skill5:
      name: Social Media
      percentage: 90%
